services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/arm64
    ports:
      - "3004:3004"
    volumes:
      - .:/app:cached
      - node_modules:/app/node_modules
      - next_data:/app/.next
      - wrangler_config:/root/.config/.wrangler
    env_file:
      - .env.local
    environment:
      - NODE_ENV=development

volumes:
  node_modules:
  next_data:
  wrangler_config:
